services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\CustomFieldsBundle\:
        resource: '../../*'
        exclude:
            - '../../Resources/'
